version: '3.2'

services:

  postgres:
    image: postgres:9.6.1
    ports:
      - '9432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
